### ISSUE TITLE
Failed to activate the scroll-searcher package - Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by krasi-georgiev** [Aakash1312/scroll-searcher#16]
TypeError: Cannot read property 'appendChild' of undefined
    at Main.on (/Users/krasimir/.atom/packages/scroll-searcher/lib/main.coffee:148:20)
    at /Users/krasimir/.atom/packages/scroll-searcher/lib/main.coffee:1:1
    at PaneContainer.module.exports.PaneContainer.observePaneItems (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:125:9)
    at Workspace.module.exports.Workspace.observePaneItems (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:339:33)
    at Main.initialize (/Users/krasimir/.atom/packages/scroll-searcher/lib/main.coffee:90:41)
    at Main.toggle (/Users/krasimir/.atom/packages/scroll-searcher/lib/main.coffee:98:8)
    at Main.activate (/Users/krasimir/.atom/packages/scroll-searcher/lib/main.coffee:51:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:191:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:164:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:94:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:299:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:312:11
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:181:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by Aakash1312** [comment]
Do you get the error every time you toggle the package?

**Comment by Aakash1312** [comment]
Please also provide the version of Atom and find-and-replace package you are using

**Comment by krasi-georgiev** [comment]
yes I get the error every time

Atom is  1.13.0

addon version is 5.0.0

**Comment by meyerweb** [comment]
I have the same Atom and package versions, and while I don’t see any errors, I also can’t seem to toggle or otherwise use scroll-searcher.  When I try to use the toggle command, either via menu or keybinding, nothing is reported in the console and nothing changes in the status bar.  I’m on OS X 10.11.6.

**Comment by Aakash1312** [comment]
Scroll searcher has been updated. Due to recent shadow dom update, this new version will only work with Atom >= v1.13.0.
https://atom.io/packages/scroll-searcher

**Comment by meyerweb** [comment]
Working fine for me now—thanks!

**Comment by Aakash1312** [comment]
Hey thank you all for your feedback :)

**Comment by krasi-georgiev** [comment]
all good for me as well
