### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidCreateMarker' of undefined

### ISSUE THREAD

**Issue by ronoc160** [Aakash1312/scroll-searcher#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.2
**Thrown From**: [scroll-searcher](https://github.com/Aakash1312/scroll-searcher) package 5.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidCreateMarker' of undefined

```
At /Users/conorbyrne/.atom/packages/scroll-searcher/lib/scroll-marker.coffee:34

TypeError: Cannot read property 'onDidCreateMarker' of undefined
    at ScrollMarker.module.exports.ScrollMarker.updateModel (/packages/scroll-searcher/lib/scroll-marker.coffee:34:70)
    at ScrollMarker.updateModel (/packages/scroll-searcher/lib/scroll-marker.coffee:1:1)
    at Main.markOnEditorChange (/packages/scroll-searcher/lib/main.coffee:132:23)
    at /packages/scroll-searcher/lib/main.coffee:1:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:493:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:16:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:280:26)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:318:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app/src/pane.js:454:25)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:419:27)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:609:22)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:685:22)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
     -2:25.7.0 project-find:show (atom-pane.pane.active)
     -2:25.5.0 core:paste (input.hidden-input)
     -2:25.2.0 core:delete (input.hidden-input)
     -2:24.2.0 core:confirm (input.hidden-input)
     -1:29.3.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:59.1.0 find-and-replace:show (input.hidden-input)
     -0:58.9.0 core:paste (input.hidden-input)
     -0:58.7.0 core:confirm (input.hidden-input)
     -0:57 project-find:show (input.hidden-input)
     -0:56.7.0 core:paste (input.hidden-input)
     -0:56.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
atom-beautify 0.29.24 
atom-typescript 11.0.6 
busy-signal 1.4.3 
emmet 2.4.3 
Hydrogen 1.13.0 
incremental-search 5.2.2 
intentions 1.1.2 
language-javascript-jsx 0.3.7 
language-vue 0.22.0 
linter 2.2.0 
linter-ui-default 1.6.2 
new-tab 0.5.3 
scroll-searcher 5.2.0 
smart-tab-name 1.0.5 
terminal-plus 0.14.5 
```

**Comment by luzpaz** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 3.1.6
**OS**: "Manjaro Linux"
**Thrown From**: [scroll-searcher](https://github.com/Aakash1312/scroll-searcher) package 5.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'onDidCreateMarker' of undefined

```
At /home/beast/.atom/packages/scroll-searcher/lib/scroll-marker.coffee:34

TypeError: Cannot read property 'onDidCreateMarker' of undefined
    at ScrollMarker.module.exports.ScrollMarker.updateModel (/packages/scroll-searcher/lib/scroll-marker.coffee:34:71)
    at ScrollMarker.updateModel (/packages/scroll-searcher/lib/scroll-marker.coffee:1:1)
    at Main.markOnEditorChange (/packages/scroll-searcher/lib/main.coffee:132:23)
    at /packages/scroll-searcher/lib/main.coffee:1:1
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/lib/atom/src/workspace.js:429:20)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/lib/atom/src/workspace-center.js:17:14)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PaneContainer.didChangeActiveItemOnPane (/usr/lib/atom/src/pane-container.js:281:20)
    at Pane.setActiveItem (/usr/lib/atom/src/pane.js:440:42)
    at Pane.activateItem (/usr/lib/atom/src/pane.js:579:12)
    at TabBarView.module.exports.TabBarView.onClick (/usr/lib/atom/node_modules/tabs/lib/tab-bar-view.js:727:19)
```

### Commands

```
     -1:34.2.0 project-find:show (div.tool-panel.tree-view)
     -1:32.4.0 core:paste (input.hidden-input)
     -1:31.3.0 core:confirm (input.hidden-input)
     -1:16.8.0 core:backspace (input.hidden-input)
  5x -1:16 editor:move-to-end-of-word (input.hidden-input)
     -1:14.7.0 core:move-right (input.hidden-input)
     -1:14 core:backspace (input.hidden-input)
     -1:10.1.0 editor:select-line (input.hidden-input)
     -1:09.7.0 core:confirm (input.hidden-input)
     -0:51.3.0 tree-view:unfocus (div.tool-panel.tree-view)
     -0:50.7.0 core:cancel (div.results-view.focusable-panel)
     -0:46.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-commander 0.12.0 
atom-html-preview 0.2.6 
atom-js-console 1.2.2 
atom-live-server 2.3.0 
busy-signal 2.0.0 
editing-diff 0.2.1 
eval-javascript 1.2.0 
ide-bash 1.0.11 
ide-python 1.3.0 
intentions 1.1.5 
line-diff-details-plus 1.9.1 
linter 2.3.0 
linter-checkbashisms 0.1.5 
linter-eslint 8.5.2 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
platformio-ide-terminal 2.9.1 
python-debugger 0.2.0 
rst-preview 1.3.1 
scroll-searcher 5.2.0 
```
