### ISSUE TITLE
Failed to activate the scroll-searcher package

### ISSUE THREAD

**Issue by Artalus** [Aakash1312/scroll-searcher#23]
Happens right after installation of the package

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [scroll-searcher](https://github.com/Aakash1312/scroll-searcher) package 5.2.0

### Stack Trace

Failed to activate the scroll-searcher package

```
At Cannot read property 'onDidUpdateState' of undefined

TypeError: Cannot read property 'onDidUpdateState' of undefined
    at Main.on (/packages/scroll-searcher/lib/main.coffee:145:74)
    at /packages/scroll-searcher/lib/main.coffee:1:1
    at PaneContainer.observePaneItems (~/AppData/Local/atom/app-1.20.0/resources/app/src/pane-container.js:107:51)
    at WorkspaceCenter.observePaneItems (~/AppData/Local/atom/app-1.20.0/resources/app/src/workspace-center.js:71:65)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/workspace.js:745:32
    at Array.map (native)
    at Workspace.observePaneItems (~/AppData/Local/atom/app-1.20.0/resources/app/src/workspace.js:744:116)
    at Main.initializePackage (/packages/scroll-searcher/lib/main.coffee:90:41)
    at Main.toggle (/packages/scroll-searcher/lib/main.coffee:98:8)
    at Main.activate (/packages/scroll-searcher/lib/main.coffee:51:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.20.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.20.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by wooooooooooooooowastaken** [comment]
Same as previously reported  except with version 1.25.0 x64 on Windows 10.
```
Cannot read property 'onDidUpdateState' of undefined

Failed to activate the scroll-searcher package

Stack Trace 

TypeError: Cannot read property 'onDidUpdateState' of undefined
    at Main.on (file:///C:/Users/myUsername/.atom/packages/scroll-searcher/lib/main.coffee:145:74)
    at file:///C:/Users/myUsername/.atom/packages/scroll-searcher/lib/main.coffee:1:1
    at PaneContainer.observePaneItems (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\pane-container.js:108:51)
    at WorkspaceCenter.observePaneItems (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\workspace-center.js:71:65)
    at CompositeDisposable.getPaneContainers.map.container (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\workspace.js:651:68)
    at Array.map (native)
    at Workspace.observePaneItems (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\workspace.js:651:41)
    at Main.initializePackage (file:///C:/Users/myUsername/.atom/packages/scroll-searcher/lib/main.coffee:90:41)
    at Main.toggle (file:///C:/Users/myUsername/.atom/packages/scroll-searcher/lib/main.coffee:98:8)
    at Main.activate (file:///C:/Users/myUsername/.atom/packages/scroll-searcher/lib/main.coffee:51:6)
    at Package.activateNow (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\package.js:230:33)
    at measure (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\package.js:206:33)
    at Package.measure (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\package.js:88:25)
    at activationPromise.Promise (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\package.js:198:38)
    at PackageManager.activatePackage (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\package-manager.js:695:42)
    at C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\node_modules\settings-view\lib\package-manager.js:491:35
    at exit (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\buffered-process.js:267:15)
    at ChildProcess.process.on (C:\Users\myUsername\AppData\Local\atom\app-1.25.0\resources\app\src\buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```
>The error was thrown from the scroll-searcher package. This issue has already been reported.
